python&Django/day18/chatproject/account/urls.py
from django.urls import path , include
from . import views
app_name = "accounts"
urlpatterns = [
    path('login/', views.login,name="login"),
    path('signup/', views.signup,name="signup"),    
    path('logout/', views.logout,name="logout"),    
]

python&Django/day18/chatproject/boards/urls.py
from django.urls import path , include
from . import views
app_name = "boards"
urlpatterns = [
    path('', views.index,name="index"),
    path('<int:room_id>/', views.show,name="room"),   
    path('<int:room_id>/exit/', views.exit,name="exit"), 
    path('chat/', views.chat,name="chat"),   
    
]

python&Django/day18/chatproject/chatproject/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('boards.urls')),
    path('account/', include('account.urls')),
]

python&Django/day18/chatproject/boards/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.
class Room(models.Model):
    title = models.CharField(max_length=32)
    code = models.CharField(max_length=16, unique=True)
    max_connection = models.IntegerField()
    master = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="rooms")
    def current_con(self):
        return len(self.users.all())
class Message(models.Model):
    contents = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    room = models.ForeignKey(Room , on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

python&Django/day18/chatproject/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
# Create your views here.

def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save() # 회원가입
            auth_login(request, user) # 로그인
            return redirect('boards:index')
        else:
            return render(request, 'signup.html')
    else:
        if request.user.is_authenticated:
            return redirect('boards:index')
        else: 
            return render(request, 'signup.html')

def login(request):
    if request.method == "POST":
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('boards:index')
        else:
            return render(request, 'login.html')
    else:
        if request.user.is_authenticated:
            return redirect('boards:index')
        else:
            return render(request, 'login.html')

def logout(request):
    auth_logout(request)
    return redirect('boards:index')

python&Django/day18/chatproject/boards/views.py
from django.shortcuts import render , redirect
from .models import Room,Message
from django.http.response import HttpResponse
import secrets
import json
import pusher
pusher_client = pusher.Pusher(
  app_id='908807',
  key='b103533a85ecae4e3e14',
  secret='##############', ### NEVER UPLOAD TO GIT
  cluster='ap3',
  ssl=True
)
def index(request):
    if request.method =="POST":
        title = request.POST["room-title"]
        max_count = request.POST["room-max-count"]
        code = secrets.token_urlsafe(16)
        room = Room()
        room.title = title
        room.max_connection= max_count
        room.code = code
        room.master_id = request.user.id
        room.save()
        room.users.add(request.user)
        current_con = room.current_con()
        context = {
            'id':room.id,
            'title':title,
            'master': room.master.username,
            'max_count':max_count,
            'current_con':current_con   
        }
        pusher_client.trigger('main', 'room-created', json.dumps(context))
        return HttpResponse('',status=204)
    else:
        # 트리거(채널, 이벤트,값)
        # 해당 채널을 구독하고 있는 녀석에게 이벤트와 값을 넘겨준다.
        rooms = Room.objects.all()
        context={
            'rooms':rooms
        }    
        return render(request , 'index.html' , context)

def show(request, room_id):
    if request.user.is_authenticated :
        room = Room.objects.get(id=room_id)
        room.users.add(request.user)
        join_message = {
            'user': request.user.username,
            'message': '님이 방에 들어왔습니다.'
        }
        pusher_client.trigger(room.code, 'chat', json.dumps(join_message))
        messages= Message.objects.filter(room_id=room.id).order_by("created_at")            
        r = room.current_con()
        con = {
            'room_id': room_id,
            'current_con': r
        }
        pusher_client.trigger('main', 'room-update', json.dumps(con))
        context={     
            'room':room,
            'messages':messages,
        }
        return render(request , 'show.html',context)
    else:
        return redirect('boards:login')
def exit(request, room_id):
    room = Room.objects.get(id=room_id)
    room.users.remove(request.user)
    r = room.current_con()
    con = {
        'room_id': room_id,
        'current_con': r
    }
    pusher_client.trigger('main', 'room-update', json.dumps(con))
    join_message = {
            'user': request.user.username,
            'message': '님이 방에서 나갔습니다.'
        }
    pusher_client.trigger(room.code, 'chat', json.dumps(join_message))
    return redirect('boards:index')
def chat(request):
    id = request.user.id
    contents = request.POST["text"]
    room = Room.objects.get(id=request.POST["room_id"])
    message = Message()
    message.contents=contents
    message.user_id=id
    message.room_id=room.id
    message.save()
    context={
        'user':request.user.username,
        'message':message.contents,        
    }
    pusher_client.trigger(room.code, 'chat', json.dumps(context))
    return HttpResponse('',status=204)

python&Django/day18/chatproject/account/templates/login.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Signin Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css" integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
    <link rel="stylesheet" href="https://getbootstrap.com/docs/4.4/examples/sign-in/signin.css">
    

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
</head>

<body class="text-center">
    <form class="form-signin" method="POST">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
        <h1 class="h3 mb-3 font-weight-normal">Please sign in</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input name="username" type="text" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input name="password" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        <a class="btn btn-lg btn-info btn-block" href="{% url 'accounts:signup' %}">Sign up</a>
        <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
    </form>
</body>

</html>

python&Django/day18/chatproject/account/templates/signup.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Signin Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/sign-in/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.0/css/bootstrap.min.css"
        integrity="sha384-SI27wrMjH3ZZ89r4o+fGIJtnzkAnFs3E4qz9DIYioCQ5l9Rd/7UAa8DHcaL8jkWt" crossorigin="anonymous">
    <link rel="stylesheet" href="https://getbootstrap.com/docs/4.4/examples/sign-in/signin.css">


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .form-signin input[type="password"] {
            margin-bottom: 0px !important;
        }
    </style>
</head>

<body class="text-center">
    <form class="form-signin" method="POST">
        <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
        <h1 class="h3 mb-3 font-weight-normal">Please sign up</h1>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input name="username" type="text" id="inputEmail" class="form-control" placeholder="Email address" required
            autofocus>
        <label for="inputPassword" class="sr-only">Password</label>
        <input name="password1" type="password" id="inputPassword" class="form-control" placeholder="Password" required>
        <label for="inputPasswordConfirmation" class="sr-only">Password Confirmation</label>
        <input name="password2" type="password" id="inputPasswordConfirmation" class="form-control"
            placeholder="Password Confirmation" required>
        <div class="checkbox mb-3">
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign up</button>
        <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
    </form>
</body>

</html>

python&Django/day18/chatproject/boards/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://js.pusher.com/5.0/pusher.min.js"></script>
    
</head>
<body>
        <nav class="navbar navbar-expand navbar-dark bg-dark">
                <a class="navbar-brand" href="#">Always expand</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample02" aria-controls="navbarsExample02" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="navbarsExample02">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="#">Link</a>
                    </li>
                  </ul>
                  <form class="form-inline my-2 my-md-0">
                    <input class="form-control" type="text" placeholder="Search">
                  </form>
                  {% if user.is_authenticated %}
                  <a class="btn btn-primary" href="{% url 'accounts:logout' %}">{{user.username}}</a>
                  {% else %}
                  <a class="btn btn-primary" href="{% url 'accounts:login' %}">login</a>
                  <a class="btn btn-primary" href="{% url 'accounts:signup' %}">signup</a>
                  {% endif %}
                </div>
              </nav>
    {% block content %}    
    {% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

python&Django/day18/chatproject/boards/templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <h1>bring me PainKiller</h1>
</div>
<div class="container">
    <div class="row">
        <table class="table table-hover table-dark text-center">
            <thead>
                <tr>
                    <th scope="col" width="5%">#</th>
                    <th scope="col" width="50%">채팅방</th>
                    <th scope="col" width="25%">방장</th>
                    <th scope="col" width="20%">인원</th>
                </tr>
            </thead>
            <tbody class="room-list">
                {% for room in rooms %}
                <tr onclick="location.href='/boards/{{room.id}}/';">
                    <th scope="row">{{room.id}}</th>
                    <td>{{room.title}}</td>
                    <td>{{room.master}}</td>
                    <td><span id="room-{{room.id}}-count">{{room.current_con}} </span>/ {{room.max_connection}}</td>
                </tr>
                {% endfor  %}
            </tbody>
        </table>
    </div>
    <div class="row">
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#makeNewChat">
            Make New Chat
        </button>

    </div>
</div>
<!-- Modal -->
<div class="modal fade" id="makeNewChat" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
    aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">채팅방 만들기</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="create-room-form">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
                <div class="modal-body">
                    <div class="input-group mb-3">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="basic-addon3">채팅방 제목</span>
                        </div>
                        <input name="room-title" type="text" class="form-control" id="basic-url"
                            aria-describedby="basic-addon3">
                    </div>
                    <div class="input-group">
                        <input name="room-max-count" type="number" class="form-control">
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">닫기</button>
                    <button id="create-room" type="button" class="btn btn-primary" data-dismiss="modal">채팅방 생성</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}
{% block script %}
<script>
    // Enable pusher logging - don't include this in production
    Pusher.logToConsole = true;
    var pusher = new Pusher('######', {
        cluster: 'ap3',
        forceTLS: true
    });

    var channel = pusher.subscribe('main');
    // 해당 채널을  구독,
    channel.bind('room-created', function (data) {
        // 해당 이벤트가 발생하면 , 작동
        var room = `<tr onclick="location.href='/boards/${data.id}/';">
            <th scope="row">${data.id}</th>
            <td>${data.title}</td>
            <td>${data.master}</td>
            <td><span id="room-${data.id}-count">${data.current_con}  </span>/ ${data.max_count}</td>
            </tr>`
        $('.room-list').append(room)
    });
    channel.bind('room-update', function (data) {
        $(`#room-${data.room_id}-count`).text(data.current_con)
    });
</script>
<script>
    $(function () {
        $('#create-room').on('click', function () {
            var roomData = $('#create-room-form').serialize();
            console.log(roomData)
            $.ajax({
                url: '{% url "boards:index" %}',
                method: 'POST',
                data: roomData,
                success: function (data) {
                    console.log(data)
                },
                error: function (data) {
                    console.log(data)

                }
            })
        });
    });
</script>
{% endblock %}

python&Django/day18/chatproject/boards/templates/show.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <h1>{{room.title}}</h1>
        <div class="col-12 chat-messages" style="overflow:auto; width: 100%; height: 250px;">
            {% for tmp in messages %}
            <p>{{tmp.user.username}} :{{tmp.contents}}</p>
            {% endfor %}
        </div>
    </div>
    <form action="#" id="chat-form">
        <div class="row">
            <div class="col-10">
                <input id="input" name="input" type="text" class="form-control">
                <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}">
                <input type="hidden" name="user_id" value="{{user.id}}">
            </div>
            <div class="col-2 text-center">
                <button type="submit" class="btn btn-success">확인</button>
            </div>
        </div>
    </form>
    <div class="row">
        <a class="exit" href="{% url 'boards:exit' room.id %}" class="btn btn-warning">나가기</a>
    </div>
</div>
{% endblock %}

{% block script %}
<script>
    $(function () {
        $('#chat-form').on('submit', function (e) {
            e.preventDefault();
            var room_id = '{{room.id}}';
            var content = $(this).find('#input').val()
            console.log(content)
            $(this).find('#input').val('')
            $.ajax({
                url: '{% url "boards:chat" %}',
                method: 'POST',
                data: {
                    room_id: room_id,
                    text: content,
                    csrfmiddlewaretoken: '{{csrf_token}}'
                },
                success: function (data) {
                    console.log("success")
                },
                error: function (data) {

                }
            })
        });
    })  
    $('.chat-messages').scrollTop($('.chat-messages')[0].scrollHeight);
    Pusher.logToConsole = true;
    var pusher = new Pusher('######', {
        cluster: 'ap3',
        forceTLS: true
    });
    var channel = pusher.subscribe('{{room.code}}');
    // 해당 채널을  구독,
    channel.bind('chat', function (data) {
        var contents = "";
        $('.chat-messages').append(`<p>${data.user} : ${data.message}<p>`);
        $('.chat-messages').scrollTop($('.chat-messages')[0].scrollHeight);
    });
</script>
{% endblock %}