python&Django/day9/crudtest/articles/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name ='articles'
urlpatterns = [
    path('', views.index,name="index"),
    path('<int:id>/',views.show,name="show"),
    path('new/',views.new,name="new"),
    path('create/',views.create,name="create"),
    path('edit/<int:id>',views.edit,name="edit"),
    path('<int:id>/update/',views.update,name="update"),
    path('<int:id>/destroy/',views.destroy,name="delete"),
]

python&Django/day9/crudtest/crudtest/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/',include('articles.urls')),
]

python&Django/day9/crudtest/articles/models.py
from django.db import models
import datetime
# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=16)
    contents = models.TextField()
    creator = models.CharField(max_length=8)
    created_at = models.DateTimeField(auto_now_add=True , null=True)
    #비어있어도 상관 없는 내용으로 넣어준거에요
    updated_at = models.DateTimeField(auto_now=True , null=True)
    def datetime_to_str(self):
        return self.created_at.strftime("%Y-%m-%d")
    def created_by(self):
        return f'{self.creator} at {self.created_at}'
    def __str__(self):
        return f'[{self.title}] - created by {self.creator}'

python&Django/day9/crudtest/articles/views.py
from django.shortcuts import render,redirect
import requests
from .models import Article
# Create your views here.
def index(request):
    articles = Article.objects.all()
    context={
        'articles':articles
    }
    return render(request,'index.html',context)

def show(request,id):
    article = Article.objects.get(id=id)
    context={
        'article':article
    }
    return render(request,'show.html',context)

def new(request):
    return render(request,'new.html')

def create(request):
    title= request.GET['title']
    contents=request.GET['contents']
    creator=request.GET['creator']    
    article=Article.objects.create(title=title,contents=contents,creator=creator)    
    return redirect('/articles/')

def edit(request,id):
    article = Article.objects.get(id=id)
    context={
        'article':article
    }
    return render(request,'edit.html',context)

def update(request,id):
    article = Article.objects.get(id=id)
    title= request.GET['title']
    contents=request.GET['contents']
    article.title=title
    article.contents=contents
    article.save()
    return redirect('/articles/')

def destroy(request,id):
    article = Article.objects.get(id=id)
    article.delete()
    return redirect('/articles/')

python&Django/day9/crudtest/articles/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

</head>
<style>
.mySelect { font-size: 2em; }
.mySelect option { color: green; }
.mySelect option[value=""] { color: red; }
.mySelect:invalid { color: red; }</style>
<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
    <a class="navbar-brand" href="#">Top navbar</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
      aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/articles/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
      </ul>
      <form class="form-inline mt-2 mt-md-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
  integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
  integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
  integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</html>

python&Django/day9/crudtest/articles/templates/edit.html
{% extends 'base.html' %}
{% block content %}
<h1>
    edit    
</h1>
<form action="/articles/{{article.id}}/update/">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control" id="Title" name="title" aria-describedby="emailHelp" value="{{article.title}}">
    </div>
    <div class="form-group">
        <label for="contents">contents</label>
        <textarea class="form-control" id="contents" name="contents" >{{article.contents}}</textarea>
    </div>
    <div class="form-group">
        <label for="creator">Creator</label>
        <input type="text" class="form-control" id="creator" name="creator" readonly="readonly" value="{{article.creator}}">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}

python&Django/day9/crudtest/articles/templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>
    index
</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th scope="col">Title</th>
            <th scope="col">Contents</th>
            <th scope="col">Creator</th>
            <th scope="col">Created At</th>
            <th scope="col">link</th>
        </tr>
    </thead>
    <tbody>
        {% for tmp in articles %}
        <tr>
            <td>{{tmp.title}}</td>
            <td>{{tmp.contents}}</td>
            <td>{{tmp.creator}}</td>
            <td>{{tmp.datetime_to_str}}</td>
            <td><a href="{% url 'articles:show' tmp.id %}">이동</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<a href="/articles/new/" class="btn btn-info">새글쓰기</a>
{% endblock %}

python&Django/day9/crudtest/articles/templates/new.html
{% extends 'base.html' %}
{% block content %}
<h1>
    new
</h1>
<form action="{% url 'articles:create' %}">
    <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control" id="Title" name="title" aria-describedby="emailHelp"
            placeholder="제목을 입력하시오">
    </div>
    <div class="form-group">
        <label for="contents">contents</label>
        <textarea class="form-control" id="contents" name="contents" placeholder="contents"></textarea>
    </div>    
    <div class="form-group">
        <label for="creator">Creator</label>
        <input type="text" class="form-control" id="creator" name="creator" placeholder="creator">
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

python&Django/day9/crudtest/articles/templates/show.html
{% extends 'base.html' %}
{% block content %}
<h1>
    {{article.title}} <br>
</h1>    
<p>{{article.contents}}</p>
<p class="text-right" >{{article.created_by}}</p>
<a href="{% url 'articles:edit' article.id %}" class="btn btn-info" >수정</a>
<a href="{% url 'articles:delete' article.id %}" class="btn btn-warning" >삭제</a>
{% endblock %}