python&Django/pothlay/crawling/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name ='live'
urlpatterns = [
    path('',views.main,name='main'),
    path('all/',views.allHTML,name='all'),
    path('slide/',views.slideTest,name='slide'),    
    path('platform/<int:platform>',views.platform,name='get_platform'),
    path('getAll/<int:platform>',views.ret_stream,name='get_all'),

    path('getslide/',views.getslide,name='get_slide'),

    path('get_main_thumb/<int:platform>',views.get_main_thumbnail , name='get_main_thumbnail'),

    path('youtube/',views.ret_youtube,name='get_youtube'),
    path('twitch/',views.ret_twitch,name='get_twitch'),
    path('afreeca/',views.ret_afreeca,name='get_afreeca'),
]

python&Django/pothlay/hotplay/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('subfunction.urls')),
    path('live/', include('crawling.urls')),
]

python&Django/pothlay/crawling/models.py
from django.db import models

# Create your models here.
class Stream(models.Model):
    id =  models.AutoField(auto_created=True,serialize=False, verbose_name='ID', primary_key=True)
    channel_name = models.CharField(max_length=300)
    channel_url = models.CharField(max_length=300, null=True)
    channel_thumbnail = models.CharField(max_length=300 , null=True)
    title = models.CharField(max_length=300)
    stream_url= models.CharField(max_length=300)
    stream_embed_url= models.CharField(max_length=300)
    stream_views = models.IntegerField()
    stream_thumbnail = models.CharField(max_length=300)
    tof = models.IntegerField(null=True)
    platform = models.IntegerField()

python&Django/pothlay/crawling/views.py
from django.shortcuts import render
from bs4 import BeautifulSoup
from selenium import webdriver
from .models import Stream
import requests
import json
import time
import random
import threading

# Create your views here.

def frequnctly():
    print("....Crawling Stared....")
    t1 = threading.Thread(target=getYoutube)
    t1.start()    
    t2 = threading.Thread(target=getTwitch)
    t2.start()    
    t3 = threading.Thread(target=getAfreeca)
    t3.start()    
    print("....Crawling End....")
    threading.Timer(600,frequnctly).start()

    return
def main(request):
    test = getbysele()
    #lives= getYoutube()
    # context= {
    #     'lives':lives,
    # }    
    # return render(request, 'main.html',context)
    data = getAfreeca()
    context = {
        'lives': data,
        'test':test
    }
    return render(request, 'main.html',context)
def slideTest(request):
    return render(request, 'slideTest.html')

def allHTML(request):    
    html = getTwitch()
    context ={
        'lives':html
    }
    return render(request, 'twitch.html',context)
def getbysele():
    
    return 
def getYoutube():
    url = 'https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig'    
    data = requests.get(url).text
    html = BeautifulSoup(data,'html.parser')
    # lives = html.select('#items .style-scope .yt-horizontal-list-renderer')
    test=html.select('.channels-content-item')
    contents = html.select('.feed-item-main-content')
    lives =[]
    length = len(test)
    for tmp in test:
        img = tmp.select_one('img')['data-thumb']
        t = (tmp.select_one('.yt-lockup-title a')['title'])
        embed =  "https://www.youtube.com/embed/"
        link  = tmp.select_one('.yt-lockup-title a')['href']
        key = link.split('=')
        embed = f'{embed}{key[1]}'
        l = (f"https://www.youtube.com{tmp.select_one('.yt-lockup-title a')['href']}")        
        channel = (tmp.select_one('.yt-user-name').text)
        vs = tmp.select_one('ul .yt-lockup-meta-info li')
        if not vs == None:
            vs = vs.text
        else:
            vs = '0'
        text_over_flag= 0        
        if len(t) > 20:
            text_over_flag= 1        
        if vs[0:2] =='시작':
            continue
        if vs[0:2] =='조회':            
            continue
        cma = vs.split('명')
        a = 0
        for tp in cma[0].split(','):
            a *=1000
            a += int(tp)
        v = a
        if Stream.objects.filter(channel_name=channel).exists():
            stream = Stream.objects.get(channel_name=channel)
        else:
            stream = Stream()   
        stream.channel_name = channel
        stream.title = t
        stream.stream_url = l
        stream.stream_embed_url = embed
        stream.stream_views = v
        stream.stream_thumbnail = img
        stream.platform = 1
        stream.tof=text_over_flag
        stream.save()
        lives.append(channel)      
    before = Stream.objects.filter(platform=1)
    for tmp in before:
        t = tmp.channel_name
        if not t in lives:
            tmp.delete()
    print("getYoutube done")
    return
def getTwitch():    
    url = "https://api.twitch.tv/kraken/streams/"
    params ={
        'language':'ko',
        'stream_type':'all',
        'limit':100,
    }  
    headers = {
        'Accept': 'application/vnd.twitchtv.v5+json',        
        'Client-ID': 'u9b5xmjbfx2meuntk2a2r5gj9ax7vc'
    }
    data = requests.get(url, params = params , headers= headers)
    jsons = data.json()['streams']
    lives= []
    length = len(jsons)
    for tmp in jsons:
        channel = tmp['channel']['display_name']
        g = tmp['game']
        name = tmp['channel']['name']
        logo = tmp['channel']['logo']
        title = tmp['channel']['status']
        thumbnail = tmp['preview']['medium']
        profile_banner = tmp['channel']['profile_banner']
        u = tmp['channel']['url']
        total_views = tmp['channel']['views']
        now_views = tmp['viewers']
        followers = tmp['channel']['followers']
        text_over_flag= 0
        if len(title) > 20:
            text_over_flag= 1
        if Stream.objects.filter(channel_name=channel).exists():
            stream = Stream.objects.get(channel_name=channel)
        else:
            stream = Stream()         
        stream.channel_name = channel
        stream.title = title
        stream.stream_url = u
        stream.stream_embed_url = f'https://player.twitch.tv/?channel={name}'
        stream.stream_views = now_views
        stream.stream_thumbnail = thumbnail
        stream.platform = 0
        stream.tof=text_over_flag
        stream.save() 
        lives.append(channel)
    before = Stream.objects.filter(platform=0)
    for tmp in before:
        t = tmp.channel_name
        if not t in lives:
            tmp.delete()
    print("getTwitch done")
    return
def getAfreeca():    
    print("getAfreeca done")
    return


def ret_youtube(request):
    stream = Stream.objects.filter(platform=1)
    lives = stream
    length = len(stream)
    context={
        'lives':lives,
        'length':length
    }
    return render(request,'subfunction/youtube.html',context)

def ret_twitch(request):
    stream = Stream.objects.filter(platform=0)
    lives = stream
    length = len(stream)
    context={
        'lives':lives,
        'length':length
    }
    return render(request,'subfunction/twitch.html',context)
def ret_afreeca(request):
    stream = Stream.objects.filter(platform=2)
    lives = stream
    length = len(stream)
    context={
        'lives':lives,
        'length':length
    }
    return render(request,'subfunction/afreeca.html',context)
def platform(request,platform):
    lives = Stream.objects.filter(platform=platform).order_by('stream_views').reverse()
    context={
        'lives':lives,
    }
    return render(request,'subfunction/sort_platform.html',context)
def ret_stream(request,platform):
    split = 0
    if platform < 3:
        stream = Stream.objects.filter(platform=platform).order_by('stream_views').reverse()
    elif platform ==3 :
        stream = Stream.objects.all().order_by('stream_views').reverse()
        split = 1
    elif platform ==4:
        stream = Stream.objects.all().order_by('stream_views').reverse()[50:100]
        split = 2
    length = len(stream)
    context={
        'lives':stream,
        'length':length,
        'split':split
    }
    return render(request,'all.html',context)
def getslide(request):    
    stream = Stream.objects.all()
    lives = list(stream)
    lives = random.sample(lives,10)
    context ={
        'lives':lives
    }
    return render(request,'carousel_slide.html',context)

def get_main_thumbnail(request, platform):
    stream = Stream.objects.filter(platform=platform).order_by('stream_views').reverse()[0:12]
    lives = stream    
    context={
        'lives':lives
    }
    return render(request,'main_thumbnail.html',context)

python&Django/pothlay/crawling/templates/all.html
            {{length}}
            <div style="float:left;">
                {% for tmp in lives %}
                <div class="card">
                    <!-- onclick="location.href='{{tmp.stream_url}}'" -->
                    <img style="height:10rem" src="{{tmp.stream_thumbnail}}" class="card-img-top" alt="...">
                    <div class="card-body text-left">
                        <div style="height:3rem">
                            <p class="font-weight-bold mb-1" data-toggle="tooltip" data-placement="top"
                                title="{{tmp.title}}">
                                {% if tmp.tof == 1 %}
                                {{tmp.title|slice:":20"}}...
                                {% else %}
                                {{tmp.title}}
                                {% endif %}
                            </p>
                        </div>
                        <div style="height:3rem; width:10rem">
                            <p class="text-monospace">{{tmp.channel_name}}
                                <span class="font-weight-lighter">{{tmp.stream_views}}</span>
                            </p>
                        </div>
                        {% if split >= 1 %}
                        <div>
                            <button class="multi-btn btn btn-primary"
                                aria-label="Radio button for following text input"
                                value="{{tmp.stream_embed_url}}"data-target="left">왼쪽</button>
                            <button class="multi-btn btn btn-primary"
                                aria-label="Radio button for following text input"
                                value="{{tmp.stream_embed_url}}"data-target="right">오른쪽</button>
                            <!-- <a href="#" class="btn btn-primary">{{tmp.stream_views}}</a> -->
                        </div>
                        {% endif %}
                    </div>
                    </div>
                    {% endfor %}
                </div>

python&Django/pothlay/crawling/templates/carousel_slide.html
{% for tmp in lives %}
<div class="carousel-item " >
    <input type="hidden" class="idstore" value="{{tmp.id}}">
    <input type="hidden" id="stream-url-{{tmp.id}}" value="{{tmp.stream_embed_url}}">
    {% comment %} <img class="slide-thumbnail"id="thumbnail-{{tmp.id}}" src="{{tmp.stream_thumbnail}}"> {% endcomment %}
    <iframe id="stream-{{tmp.id}}"class="d-block w-100" width="640" height="360" src=""
        frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
        allowfullscreen></iframe>
</div>
{% endfor %}

python&Django/pothlay/crawling/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
</head>
<body>   
    {{test}}
    <h1>this is main</h1>
    <table class="table table-striped table-bordered table-hover">            
        <thead class="thead-light">
                <th scope="col">img</th>
                <th scope="col">title</th>
                <th scope="col">links</th>
                <th scope="col">channel</th>
                <th scope="col">viewer</th>
            </thead>
            <tbody>        
                {% for tmp in test %}                
                <tr>
                    {{tmp}}
                </tr>
                {% endfor %}       
            </tbody>
        </table>
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>
</body>
</html>

python&Django/pothlay/crawling/templates/main_thumbnail.html
<div class="salerow salerow3 multiline">
    {% for  tmp in lives %}
    <a class="sale_capsule app_impression_tracked" data-ds-appid="787480"
        href="{{tmp.stream_url}}" target="_blank">
        <div class="sale_capsule_image_ctn">
            <div class="sale_capsule_image_hover"></div><img class="sale_capsule_image autosize"
            src="{{tmp.stream_thumbnail}}">
        </div>
        <div class="discount_block  discount_block_inline" data-price-final="2112000">
            <div class="discount_pct">{{tmp.title}}</div>
            <div class="discount_prices">
                <div class="discount_original_price"></div>
                <div class="discount_final_price">{{tmp.channel_name}} / {{tmp.stream_views}}</div>
            </div>
        </div>
    </a>
    {% endfor %}
</div>

python&Django/pothlay/crawling/templates/slideTest.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
</head>
<style>
    .container {
        
    }

    .w-30 {
        margin: auto;
        float: left;
        width: 20rem;
    }
</style>

<body>
    
    <div id="carouselExampleControls" class="carousel slide" style="width:50%;" data-ride="carousel"
        data-interval="false">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <iframe class="d-block w-100" width="500" height="300" src="https://www.youtube.com/embed/v5IYlkZEPxA"
                    frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
            </div>
            <div class="carousel-item">
                <iframe class="d-block w-100" width="500" height="300"
                    src="http://play.afreecatv.com/ehdgkr6283/219030378" frameborder="0"
                    allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
            </div>
            <div class="carousel-item">
                <iframe class="d-block w-100" width="500" height="300" src="https://player.twitch.tv/?channel=scump"
                    frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                    allowfullscreen></iframe>
            </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    <div class="container">
        <span class="w-30">
            <table class="table table-striped table-bordered table-hover youtube">
                <thead class="thead-light">
                    <th scope="col">Youtube</th>
                </thead>
                <td id="youtube-be4">
                    <img src="https://media.giphy.com/media/jAYUbVXgESSti/giphy.gif">
                </td>
            </table>
        </span>
        <span class="w-30">
            <table class="table table-striped table-bordered table-hover twitch">
                <thead class="thead-light">
                    <th scope="col">Twitch</th>
                </thead>
                <td id="twitch-be4">
                    <img src="https://media.giphy.com/media/jAYUbVXgESSti/giphy.gif">
                </td>
            </table>

        </span>
        <span class="w-30">
            <table class="table table-striped table-bordered table-hover afreeca">
                <thead class="thead-light">
                    <th scope="col">Afreeca</th>
                </thead>
                <td id="afreeca-be4">
                    <img src="https://media.giphy.com/media/jAYUbVXgESSti/giphy.gif">
                </td>
            </table>
        </span>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    <script src="https://kit.fontawesome.com/41ac120a10.js" crossorigin="anonymous"></script>
    <script>
        $(function () {
            $('#carouselExampleControls').on('slide.bs.carousel',
                function () { //슬라이드가 이동 할 때 마다.                                 
                    var currentIndex = $('div.active').index() + 1; // 현재 슬라이드
                    var totalIndex = $('.carousel-item').length; // 전체 슬라이드
                })
            // 해당 줄(list)을 하나 삭제해야함
            var id = $(this).data('id');
            console.log(id);
            $.ajax({
                url: '{% url "live:get_youtube" %}',
                method: 'POST',
                data: {
                    csrfmiddlewaretoken: '{{csrf_token}}' // post로 보내주기 때문에 필요해
                },
                success: function (data) {
                    $('#youtube-be4').hide()
                    $('.youtube').append(data);
                },
                error: function (data) {
                    alert("youtube fail");
                }
            })
            $.ajax({
                url: '{% url "live:get_twitch" %}',
                method: 'POST',
                data: {
                    csrfmiddlewaretoken: '{{csrf_token}}' // post로 보내주기 때문에 필요해
                },
                success: function (data) {
                    $('#twitch-be4').hide()
                    $('.twitch').append(data);
                },
                error: function (data) {
                    alert("twitch fail");
                }
            })
            $.ajax({
                url: '{% url "live:get_afreeca" %}',
                method: 'POST',
                data: {
                    csrfmiddlewaretoken: '{{csrf_token}}' // post로 보내주기 때문에 필요해
                },
                success: function (data) {
                    $('#afreeca-be4').hide()
                    $('.afreeca').append(data);
                },
                error: function (data) {
                    alert("afreeca fail");                }
            })
        });
    </script>
</body>

</html>