python&Django/soffia/game/game/urls.py
from django.contrib import admin
from django.urls import path ,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('sofifa/', include('poten.urls')),
    
]

python&Django/soffia/game/poten/urls.py
from django.contrib import admin
from django.urls import path
from . import views


app_name ='sofifa'
urlpatterns = [
    path('',views.dblist,name='dblist'),
    path('load/', views.all, name='load'),    
    path('comment/', views.comment,name='comment'),
    path('<position>/', views.search,name='search'),
]

python&Django/soffia/game/poten/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField

# Create your models here.
class Player(models.Model):
    #primary key 는 name 인데 id 를 찾고 있다.
    #
    psa = models.CharField(max_length=50)
    name = models.CharField(max_length=50, primary_key=True)
    nick = models.CharField(max_length=50)    
    age = models.CharField(max_length=50) 
    overAll = models.CharField(max_length=50) 
    potential = models.CharField(max_length=50) 
    id = models.CharField(max_length=50) 
    team_flag = models.CharField(max_length=200)
    team = models.CharField(max_length=50)
    nation = models.CharField(max_length=50)
    nation_flag = models.CharField(max_length=40)
    position = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    def getPosition(self):
        ret = ''
        posis=self.position.split('/')
        for tmp in posis:
            ret+= tmp+" "
        return ret
    def comments(self):
        return Comment.objects.filter(target_id=self.name)
class Comment(models.Model):
    contents = models.TextField()
    target = models.ForeignKey(Player,on_delete=models.CASCADE)

python&Django/soffia/game/poten/views.py
from django.shortcuts import render , redirect
import requests
from bs4 import BeautifulSoup
from .models import Player,Comment
import logging
logger = logging.getLogger(__name__)

# Create your views here.
def all(request):
    url = 'https://sofifa.com/'
    data = requests.get(url).text
    html = BeautifulSoup(data,'html.parser')    
    player={}
    ages={}
    table= html.select('tr')
    titles = []
    ## 일단 선수의 정보를 dictionary 로 넣자
    for line in table:       
        name = line.select_one('.col-name .nowrap')
        age = line.select_one('.col-ae')
        posi = line.select('.col-name .pos')
        ova = line.select_one('.col-oa .p')
        poten = line.select_one('.col-pt .p')
        posis =[]
        for pos in posi:
            posis.append(pos.text)
        if name is None:
            continue
        pic = line.select_one('.col-avatar .player-check')
        flag = line.select('td .bp3-text-overflow-ellipsis a')        
        nation = flag[0]['title']
        nation_flag = flag[0].select_one('img')['data-src']
        team_flag = line.select_one('img.team')['data-src']
        team_name = flag[2].text
        id = name['href']
        ids = id.split('/')
        id = ids[2]
        player[name['title']] = {
            'nick':name.text,
            'pos':posis,
            'ova':ova.text,
            'poten':poten.text,
            'age':age.text,
            'img':pic['data-src'],
            'id':id,
            'nation':nation,
            'nation_flag':nation_flag,
            'team_name':team_name,
            'team_flag':team_flag
        }
        pos_str=""
        for tmp in posis:
            pos_str+='/'+tmp
        this= Player()
        this.psa = pic['data-src']
        this.name = name['title']
        this.nick=name.text      
        this.age = age.text
        this.overAll=ova.text
        this.potential = poten.text
        this.id=id
        this.team_flag=team_flag
        this.team=team_name
        this.nation = nation
        this.position = pos_str
        this.save()
    context = {
        'data':player
    }
    return render(request, 'sofifa.html', context)
def search(request,position):
    all_players= Player.objects.all()
    targetPlayer=[]
    for tmp in all_players:
        posis = tmp.position.split('/')        
        for p_tmp in posis:
            if p_tmp == position:
                targetPlayer.append(tmp)    
    context = {
        'players':targetPlayer
    }    
    return render(request, 'fifa/sofifaList.html', context)

def getStat(id):
    url =f'https://sofifa.com/player/{id}'
    data = requests.get(url).text
    html = BeautifulSoup(data,'html.parser')
    special = html.select_one('.bp3-card .teams')
    li = special.select('li')
    # print(li[1])
    # print(li[2])
    # print(li[3])
    # print(li[4])
    stat={}
    return li[0]
def dblist(request):
    players = Player.objects.all()
    # logger.debug(players)
    context={
        'players': players,
        'size':len(players)
    }
    return render(request, 'fifa/sofifaList.html', context)

def player_deleteAll():
    players = Player.objects.all()
    for tmp in players:
        tmp.delete()
    return 
def comment_deleteAll():
    comments = Comment.objects.all()
    for tmp in comments:
        tmp.delete()
    return 

def comment(request):
    print("---------------")
    id=request.POST['id']
    txt=request.POST['contents']
    target_p = Player.objects.get(name=id)
    comment= Comment()
    comment.target_id=target_p
    comment.contents=txt
    comment.save()
    print(comment.target_id)
    return redirect('/sofifa/')
    

python&Django/soffia/game/poten/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

</head>
{% block stylesheet %}
{% endblock %}

<body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
        <a class="navbar-brand" href="#">Top navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
            aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/sofifa/">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sofifa:dblist' %}">DBList</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'sofifa:load' %}">LoadData</a>
                </li>
            </ul>
            <form class="form-inline mt-2 mt-md-0" action="">
                <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                <select>
                    <option value="GK">GK</option>
                    <option value="CB">CB</option>
                    <option value="LB">LB</option>
                </select>
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</body>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
    integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
    integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
    integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
</script>

</html>

python&Django/soffia/game/poten/templates/sofifa.html
{% extends 'base.html' %}
{% block content %}
    <table class="table table-striped table-bordered table-hover">
        <thead class="thead-light">
            <th scope="col">avatar</th>
            <th scope="col">name</th>
            <th scope="col">nick</th>
            <th scope="col">position</th>
            <th scope="col">age</th>
            <th scope="col">overAll</th>
            <th scope="col">potential</th>
            <th scope="col">team</th>
            <th scope="col">nation</th>
        </thead>
        <tbody>
            {% for key,val in data.items %}
            <tr onClick="location.href='http://sofifa.com/player/{{val.id}}'" class="player" >
                <td>
                    <image src="{{val.img}}">
                </td>
                <td>{{key}}</td>
                <td>{{val.nick}}</td>
                <td>{{val.pos}}</td>                
                <td>{{val.age}}</td>
                <td class="numbs">{{val.ova}}</td>
                <td class="numbs">{{val.poten}}</td>
                <td>
                    <image src="{{val.team_flag}}"></image><p>{{val.team_name}}</p>
                </td>
                <td>
                    <image src="{{val.nation_flag}}"></image><p>{{val.vation}}</p>
                </td>
                <td><svg data-icon="star" height="16" viewbox="0 0 16 16" width="16"><path d="M8 0l2.5 5.3 5.5.8-4 4.1.9 5.8L8 13.3 3.1 16l.9-5.8-4-4.1 5.5-.8z" fill-rule="evenodd"></path></svg></td>

                <td>{{val.stat}}</td>
                <td>{{val}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}